name: Linting

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  lint:
    name: Lint (${{ matrix.task }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        task:
          - css
          - js
          # - md-docs
          # - md-js
          - pkg-json

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run CSS lint
        if: matrix.task == 'css'
        run: npm run lint:css

      - name: Run JS lint
        if: matrix.task == 'js'
        run: npm run lint:js

      # - name: Run Markdown docs lint
      #   if: matrix.task == 'md-docs'
      #   run: npm run lint:md:docs

      # - name: Run Markdown JS lint
      #   if: matrix.task == 'md-js'
      #   run: npm run lint:md:js

      - name: Run package.json lint
        if: matrix.task == 'pkg-json'
        run: npm run lint:pkg-json
