name: PHP Code Quality

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  php-quality:
    name: PHP Code Quality (${{ matrix.tool }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tool:
          - phpcs
          - phpstan

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Run PHPCS
        if: matrix.tool == 'phpcs'
        run: vendor/bin/phpcs

      - name: Run PHPStan
        if: matrix.tool == 'phpstan'
        run: vendor/bin/phpstan analyze
